### ISSUE TITLE
Enable Cloudfront Caching

### ISSUE THREAD

**Issue by GerDner** [Mercateo/serverless-image-processor#25]
How can i enable Caching in Cloudfront.
Im getting `x-cache: Miss from cloudfront` for every call.

**Comment by otbe** [comment]
Thanks for reporting!

Ive added a default cache control header [here](https://github.com/Mercateo/serverless-image-processor/blob/master/src/index.ts#L39).

Nevertheless you shouldn't get `x-cache: Miss from cloudfront` for every request. Do you use the cloudfront url?
Please have a look at https://d1tk3y1sqx2xzp.cloudfront.net/test.png?width=200

**Comment by GerDner** [comment]
Thanks, your quick Feedback helped me. I think i misunderstood the workflow. Now it works!
Thanks for your awesome work!
