### ISSUE TITLE
Just return File if not supported

### ISSUE THREAD

**Issue by kations** [Mercateo/serverless-image-processor#32]
Hi and thanks for the package, is it possible to return just the file (svg/pdf etc.) if  !isSupportedInputMime(inputMime)? Would be great to know how I can return the untransformed file.

Thanks

**Comment by kations** [comment]
No Problem :) your code works perfect. The use case is for .svgs and .pdfs so I think it should work.
Thanks

**Comment by otbe** [comment]
Especially for pdfs and other stuff like this we use a dedicated cloudfront origin (`/docs` points to another S3 bucket) but this should work aswell :)

Can we close this?

**Comment by kations** [comment]
Do you have performance concerns on this approach? In our case we have just one Bucket where different clients store various data via one application. 

Yes can be closed

**Comment by otbe** [comment]
Our docs (technical documentation) are quite large in size and like mentioned above it takes a huge amount of time to stream it through the lambda compared to a simple cloudfront link. Nevertheless I would just give it a try :)
